severity: error
rules :
    mixin-name-format : false
    class-name-format : false
    no-important : false
    empty-line-between-blocks: false
linters:
  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
